print('Hagamos una division')
num1=int(input('x='))
num2=int(input('dividido por:'))
print(f'La división entre {num1} y {num2} nos da {int(num1/num2)} ' )
print(f'Entonces su resto será de {num1%num2} ')